//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIInterface.Resources.HomeResource", typeof(HomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action List - Cars overdue &amp; un-paid cases.
        /// </summary>
        public static string ActionList {
            get {
                return ResourceManager.GetString("ActionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Business Controls (ABC&apos;s).
        /// </summary>
        public static string AllBusinessC {
            get {
                return ResourceManager.GetString("AllBusinessC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation of a vehicle.
        /// </summary>
        public static string Allocationof {
            get {
                return ResourceManager.GetString("Allocationof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated Pricing &amp; discounts.
        /// </summary>
        public static string AutomatedPricing {
            get {
                return ResourceManager.GetString("AutomatedPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking/Reservations.
        /// </summary>
        public static string BookingReservations {
            get {
                return ResourceManager.GetString("BookingReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaReS.
        /// </summary>
        public static string CaReS {
            get {
                return ResourceManager.GetString("CaReS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rental.
        /// </summary>
        public static string CarRental {
            get {
                return ResourceManager.GetString("CarRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chauffeurs, Insurances &amp; Services selection.
        /// </summary>
        public static string ChauffeursInsurances {
            get {
                return ResourceManager.GetString("ChauffeursInsurances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Us.
        /// </summary>
        public static string ChooseUs {
            get {
                return ResourceManager.GetString("ChooseUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s Short URL.
        /// </summary>
        public static string CompanyShortURL {
            get {
                return ResourceManager.GetString("CompanyShortURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Profitability Analysis (CPA).
        /// </summary>
        public static string CustomerProfitability {
            get {
                return ResourceManager.GetString("CustomerProfitability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily reports &amp; dashboard features provide instant analysis of your daily features..
        /// </summary>
        public static string Dailyreports {
            get {
                return ResourceManager.GetString("Dailyreports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Management.
        /// </summary>
        public static string DashboardManagement {
            get {
                return ResourceManager.GetString("DashboardManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy doing business with us!.
        /// </summary>
        public static string EnjoyDoing {
            get {
                return ResourceManager.GetString("EnjoyDoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastic Support.
        /// </summary>
        public static string FantasticSupport {
            get {
                return ResourceManager.GetString("FantasticSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible Customer Age Policies.
        /// </summary>
        public static string FlexibleCustomer {
            get {
                return ResourceManager.GetString("FlexibleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Filling.
        /// </summary>
        public static string FuelFilling {
            get {
                return ResourceManager.GetString("FuelFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed increase in.
        /// </summary>
        public static string GuaranteedIncrease {
            get {
                return ResourceManager.GetString("GuaranteedIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter Branch Transfers.
        /// </summary>
        public static string InterBranch {
            get {
                return ResourceManager.GetString("InterBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a scalable application suite which is designed by highly qualified staff with decades of experience in car rental industry. It gives its customers, a privilege to customize pricing, define rates based on vehicles classification, define packages, create and configure branches..
        /// </summary>
        public static string isScalable {
            get {
                return ResourceManager.GetString("isScalable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Performance Indicators.
        /// </summary>
        public static string KeyPerformanceIndicators {
            get {
                return ResourceManager.GetString("KeyPerformanceIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Features.
        /// </summary>
        public static string MainFeatures {
            get {
                return ResourceManager.GetString("MainFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management controlled up-gradation policies.
        /// </summary>
        public static string Managementcontrolled {
            get {
                return ResourceManager.GetString("Managementcontrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string MenuBenefits {
            get {
                return ResourceManager.GetString("MenuBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string MenuOverview {
            get {
                return ResourceManager.GetString("MenuOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request A Demo.
        /// </summary>
        public static string MenuRequestDemo {
            get {
                return ResourceManager.GetString("MenuRequestDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MenuServices {
            get {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string MenuSignup {
            get {
                return ResourceManager.GetString("MenuSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App.
        /// </summary>
        public static string MobileApp {
            get {
                return ResourceManager.GetString("MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile platform provides an opportunity to reach a large number of people and mark your valuable presence..
        /// </summary>
        public static string Mobileplatform {
            get {
                return ResourceManager.GetString("Mobileplatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Vehicle Periodic Inspection.
        /// </summary>
        public static string MotorVehicle {
            get {
                return ResourceManager.GetString("MotorVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Revenue, KM analysis.
        /// </summary>
        public static string NonRevenue {
            get {
                return ResourceManager.GetString("NonRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trespassing of Mileage.
        /// </summary>
        public static string NotrespassingofMileage {
            get {
                return ResourceManager.GetString("NotrespassingofMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Reservation.
        /// </summary>
        public static string OnlineReservation {
            get {
                return ResourceManager.GetString("OnlineReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our.
        /// </summary>
        public static string Our {
            get {
                return ResourceManager.GetString("Our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Contacts.
        /// </summary>
        public static string OurContacts {
            get {
                return ResourceManager.GetString("OurContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our dedicated team provides quick response ready to help you at no additional charge..
        /// </summary>
        public static string Ourdedicatedteam {
            get {
                return ResourceManager.GetString("Ourdedicatedteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Maintenance.
        /// </summary>
        public static string PeriodicMaintenance {
            get {
                return ResourceManager.GetString("PeriodicMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill the Form.
        /// </summary>
        public static string PleaseFill {
            get {
                return ResourceManager.GetString("PleaseFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Control.
        /// </summary>
        public static string PricingControl {
            get {
                return ResourceManager.GetString("PricingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Agreements.
        /// </summary>
        public static string RentalAgreements {
            get {
                return ResourceManager.GetString("RentalAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted forward date Rental Agreement Opening.
        /// </summary>
        public static string RestrictedFor {
            get {
                return ResourceManager.GetString("RestrictedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Type Password.
        /// </summary>
        public static string ReTypePass {
            get {
                return ResourceManager.GetString("ReTypePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Analysis.
        /// </summary>
        public static string RiskAnalysis {
            get {
                return ResourceManager.GetString("RiskAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales analysis, Gross Profits, Profit and Loss.
        /// </summary>
        public static string SalesAnalysis {
            get {
                return ResourceManager.GetString("SalesAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Permissions on Back Dated Rental Agreement Closing.
        /// </summary>
        public static string SpecialPermissions {
            get {
                return ResourceManager.GetString("SpecialPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Managing your Fleet, Pricing and Customers..
        /// </summary>
        public static string StartManaging {
            get {
                return ResourceManager.GetString("StartManaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Rental .
        /// </summary>
        public static string StartYourRental {
            get {
                return ResourceManager.GetString("StartYourRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Revenue Ticket.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System allows third party partner web-sites to get available vehicles &amp; costing information..
        /// </summary>
        public static string Systemallows {
            get {
                return ResourceManager.GetString("Systemallows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking of vehicle’s movement &amp; its condition.
        /// </summary>
        public static string Trackingof {
            get {
                return ResourceManager.GetString("Trackingof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilization rates (On road, Off road - Time analysis).
        /// </summary>
        public static string UtilizationRates {
            get {
                return ResourceManager.GetString("UtilizationRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Grant to Management.
        /// </summary>
        public static string VehicleGrant {
            get {
                return ResourceManager.GetString("VehicleGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 Vehicle Movement details.
        /// </summary>
        public static string VehicleMov {
            get {
                return ResourceManager.GetString("VehicleMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Up-gradation &amp; replacement.
        /// </summary>
        public static string VehicleUp {
            get {
                return ResourceManager.GetString("VehicleUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why to.
        /// </summary>
        public static string Whyto {
            get {
                return ResourceManager.GetString("Whyto", resourceCulture);
            }
        }
    }
}
