//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RentalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RentalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIInterface.Resources.RentalResource", typeof(RentalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-off Date.
        /// </summary>
        public static string DropoffDate {
            get {
                return ResourceManager.GetString("DropoffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-off Location.
        /// </summary>
        public static string DropoffLocation {
            get {
                return ResourceManager.GetString("DropoffLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropping Off Hour.
        /// </summary>
        public static string DroppingOffHour {
            get {
                return ResourceManager.GetString("DroppingOffHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel Free to Say Hello.
        /// </summary>
        public static string FeelFree {
            get {
                return ResourceManager.GetString("FeelFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Car.
        /// </summary>
        public static string FindaCar {
            get {
                return ResourceManager.GetString("FindaCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Car.
        /// </summary>
        public static string FindCar {
            get {
                return ResourceManager.GetString("FindCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Us.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in Touch With Us.
        /// </summary>
        public static string GetinTouch {
            get {
                return ResourceManager.GetString("GetinTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s address.
        /// </summary>
        public static string Locationaddress {
            get {
                return ResourceManager.GetString("Locationaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Info.
        /// </summary>
        public static string LocationInfo {
            get {
                return ResourceManager.GetString("LocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s phone.
        /// </summary>
        public static string Locationphone {
            get {
                return ResourceManager.GetString("Locationphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picking Up Hour.
        /// </summary>
        public static string PickingUpHour {
            get {
                return ResourceManager.GetString("PickingUpHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-Up Date.
        /// </summary>
        public static string PickUpDate {
            get {
                return ResourceManager.GetString("PickUpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-Up Location.
        /// </summary>
        public static string PickUpLocation {
            get {
                return ResourceManager.GetString("PickUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Cheap Rental Cars Wherever Your Are.
        /// </summary>
        public static string SearchforCheap {
            get {
                return ResourceManager.GetString("SearchforCheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email....
        /// </summary>
        public static string Sendingemail {
            get {
                return ResourceManager.GetString("Sendingemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Map.
        /// </summary>
        public static string ShowMap {
            get {
                return ResourceManager.GetString("ShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Phone.
        /// </summary>
        public static string SupportPhone {
            get {
                return ResourceManager.GetString("SupportPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who we Are?.
        /// </summary>
        public static string WhoweAre {
            get {
                return ResourceManager.GetString("WhoweAre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours: 09:30 - 21:00 except on Sundays.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are always welcome to Contact us at the following..
        /// </summary>
        public static string Youarealways {
            get {
                return ResourceManager.GetString("Youarealways", resourceCulture);
            }
        }
    }
}
