//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelectCarResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectCarResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIInterface.Resources.SelectCarResource", typeof(SelectCarResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a car.
        /// </summary>
        public static string Choosecar {
            get {
                return ResourceManager.GetString("Choosecar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose extras.
        /// </summary>
        public static string Chooseextras {
            get {
                return ResourceManager.GetString("Chooseextras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create request.
        /// </summary>
        public static string Createrequest {
            get {
                return ResourceManager.GetString("Createrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Charge.
        /// </summary>
        public static string GetCharge {
            get {
                return ResourceManager.GetString("GetCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Airbag.
        /// </summary>
        public static string NoofAirbag {
            get {
                return ResourceManager.GetString("NoofAirbag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Doors.
        /// </summary>
        public static string NoofDoors {
            get {
                return ResourceManager.GetString("NoofDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.of Passengers.
        /// </summary>
        public static string NoofPassengers {
            get {
                return ResourceManager.GetString("NoofPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Suitcases.
        /// </summary>
        public static string NoofSuitcases {
            get {
                return ResourceManager.GetString("NoofSuitcases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Book.
        /// </summary>
        public static string ReviewBook {
            get {
                return ResourceManager.GetString("ReviewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select The Car You Want.
        /// </summary>
        public static string SelectTheCar {
            get {
                return ResourceManager.GetString("SelectTheCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Reservation Date/Time.
        /// </summary>
        public static string UpdateReservationDateTime {
            get {
                return ResourceManager.GetString("UpdateReservationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Maker.
        /// </summary>
        public static string VehicleMaker {
            get {
                return ResourceManager.GetString("VehicleMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        public static string VehicleModel {
            get {
                return ResourceManager.GetString("VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model-Year.
        /// </summary>
        public static string VehicleModelYear {
            get {
                return ResourceManager.GetString("VehicleModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cars.
        /// </summary>
        public static string ViewCars {
            get {
                return ResourceManager.GetString("ViewCars", resourceCulture);
            }
        }
    }
}
